{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-paws.storage
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paws.storage_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paws.storage/paws.storage_{{ version }}.tar.gz
  sha256: fd424b731c5160ed8d2442a0dc2710bcb36ccf4a71a8e9f53f818fb22dfb3524

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-paws.common >=0.3.0
  run:
    - r-base
    - r-paws.common >=0.3.0

test:
  commands:
    - $R -e "library('paws.storage')"           # [not win]
    - "\"%R%\" -e \"library('paws.storage')\""  # [win]

about:
  home: https://github.com/paws-r/paws
  license: Apache-2.0
  summary: Interface to 'Amazon Web Services' storage services, including 'Simple Storage Service' ('S3') and more <https://aws.amazon.com/>.
  license_family: APACHE
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - achimgaedke

# Package: paws.storage
# Title: 'Amazon Web Services' Storage Services
# Version: 0.1.12
# Authors@R: c(person(given = "David", family = "Kretch", role = c("aut", "cre"), email = "david.kretch@gmail.com"), person(given = "Adam", family = "Banker", role = "aut", email = "adam.banker39@gmail.com"), person(given = "Amazon.com, Inc.", role = "cph"))
# Description: Interface to 'Amazon Web Services' storage services, including 'Simple Storage Service' ('S3') and more <https://aws.amazon.com/>.
# License: Apache License (>= 2.0)
# URL: https://github.com/paws-r/paws
# BugReports: https://github.com/paws-r/paws/issues
# Imports: paws.common (>= 0.3.0)
# Suggests: testthat
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# Collate: 'backup_service.R' 'backup_interfaces.R' 'backup_operations.R' 'dlm_service.R' 'dlm_interfaces.R' 'dlm_operations.R' 'efs_service.R' 'efs_interfaces.R' 'efs_operations.R' 'fsx_service.R' 'fsx_interfaces.R' 'fsx_operations.R' 'glacier_service.R' 'glacier_interfaces.R' 'glacier_operations.R' 's3_service.R' 's3_operations.R' 's3_custom.R' 's3_interfaces.R' 's3control_service.R' 's3control_interfaces.R' 's3control_operations.R' 'storagegateway_service.R' 'storagegateway_interfaces.R' 'storagegateway_operations.R'
# NeedsCompilation: no
# Packaged: 2021-08-22 18:53:27 UTC; david.kretch
# Author: David Kretch [aut, cre], Adam Banker [aut], Amazon.com, Inc. [cph]
# Maintainer: David Kretch <david.kretch@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-08-22 19:30:02 UTC
